force-app/main/default/objects/Parts_Inventory__c/Parts_Inventory__c.object-meta.xml
<CustomObject>
    <label>Parts Inventory</label>
    <nameField>
        <label>Parts Inventory Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Inventory_Transaction__c/Parts_Inventory_Transaction__c.object-meta.xml
<CustomObject>
    <label>Parts Inventory Transaction</label>
    <nameField>
        <label>Parts Inventory Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Inventory_Transaction__c/fields/Confirmed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parts_Inventory_Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Parts_Inventory_Transaction__c/fields/Parts_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Parts_Inventory__c</fullName>
    <label>Parts Inventory</label>
    <referenceTo>Parts_Inventory__c</referenceTo>
    <relationshipLabel>Parts Inventory Transaction</relationshipLabel>
    <relationshipName>Parts_Inventory_Transaction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parts_Inventory_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Replenished</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Adjusted</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parts_Inventory_Transaction__c/fields/Updated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Updated_Quantity__c</fullName>
    <label>Updated Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TransactionController.cls
public with sharing class TransactionController {
    @AuraEnabled
    public static void createTrans(Decimal UQuantity, Decimal CQuantity, Datetime TDate, string Status, string Description, string PInventory){
        
        Parts_Inventory_Transaction__c p = new Parts_Inventory_Transaction__c(

            Updated_Quantity__c = UQuantity,
            Confirmed_Quantity__c = CQuantity,
            Transaction_Date__c = TDate,
            Status__c = Status,
            Description__c = Description,
            Parts_Inventory__c = PInventory
        );
        insert p;

    }

}