force-app/main/default/objects/Parts_Market_Factor__c/Parts_Market_Factor__c.object-meta.xml
<CustomObject>
    <label>Parts Market Factor</label>
    <nameField>
        <displayFormat>PMF-{00000}</displayFormat>
        <label>Parts Market Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Market_Factor__c/fields/Market_Factor__c.field-meta.xml
<CustomField>
    <fullName>Market_Factor__c</fullName>
    <label>Market Factor</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCode__c</fullName>
    <label>AMOSProductCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSSAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSSAC__c</fullName>
    <label>AMOSSAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAC__c.field-meta.xml
<CustomField>
    <fullName>SAC__c</fullName>
    <label>SAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MarketFactorTriggerTest.cls
@isTest
private class MarketFactorTriggerTest {
    @TestSetup
    static void makeData(){
        Product2 product = new Product2(Name = 'Test Product',
                                        AMOSSAC__c = '20a',
                                        MSRP__c = 100,
                                        AMOSProductCode__c = 'TEST200');

        insert product;  
    }

    @isTest
    static void updateMarketFactor(){

        Parts_Market_Factor__c mf = new Parts_Market_Factor__c(SAC__c = '20a', Market_Factor__c = 2);
        insert mf;     

        mf.Market_Factor__c = 3;

        Test.startTest();
        Database.SaveResult result = Database.update(mf, true);
        Test.stopTest();
        
        if (result.isSuccess()) {
            System.debug(result.getId());
        }
        
        if(result.getErrors().size() > 0){
            System.debug(result.getErrors()[0].getMessage());
        }
    }

}