force-app/main/default/objects/Parts_Market_Factor__c/Parts_Market_Factor__c.object-meta.xml
<CustomObject>
    <label>Parts Market Factor</label>
    <nameField>
        <displayFormat>PMF-{00000}</displayFormat>
        <label>Parts Market Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Market_Factor__c/fields/Market_Factor__c.field-meta.xml
<CustomField>
    <fullName>Market_Factor__c</fullName>
    <label>Market Factor</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCode__c</fullName>
    <label>AMOSProductCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSSAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSSAC__c</fullName>
    <label>AMOSSAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NRRP__c.field-meta.xml
<CustomField>
    <fullName>NRRP__c</fullName>
    <label>NRRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAC__c.field-meta.xml
<CustomField>
    <fullName>SAC__c</fullName>
    <label>SAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductTriggerTest.cls
@isTest
private class ProductTriggerTest {
@TestSetup
static void makeData(){
    Parts_Market_Factor__c mf = new Parts_Market_Factor__c(SAC__c = '20a', Market_Factor__c = 2);
    insert mf;                                                       
    }

    @isTest
    static void upsertProductWithRelatedSac() {

        Parts_Market_Factor__c mf = [SELECT Id, SAC__c, Market_Factor__c FROM Parts_Market_Factor__c WHERE SAC__c = '20a'];
        Product2 product = new Product2(Name = 'Test Product',
        AMOSSAC__c = '20a',
        MSRP__c = 100,
        NRRP__c = 100 * mf.Market_Factor__c,
        AMOSProductCode__c = 'TEST200');
        
        Test.startTest();
        System.debug('AMOSSAC__c : ' + product.AMOSSAC__c);
        System.debug('MSRP__c : ' + product.MSRP__c);
        System.debug('NRRP__c : ' + product.NRRP__c);
        Database.UpsertResult result = Database.upsert(product, true);
        Test.stopTest();
        
        if (result.isSuccess()) {
            System.debug(result.getId());
        }
        
        if(result.getErrors().size() > 0){
            System.debug(result.getErrors()[0].getMessage());
        }
    }

    @isTest
    static void upsertProductWithoutRelatedSac() {

        Product2 product = new Product2(Name = 'Test Product',
        AMOSSAC__c = ' ',
        MSRP__c = 100,
        NRRP__c = 100 * 1,
        AMOSProductCode__c = 'TEST200');
        
        Test.startTest();
        System.debug('AMOSSAC__c : ' + product.AMOSSAC__c);
        System.debug('MSRP__c : ' + product.MSRP__c);
        System.debug('NRRP__c : ' + product.NRRP__c);
        Database.UpsertResult result = Database.upsert(product, true);
        Test.stopTest();
        
        if (result.isSuccess()) {
            System.debug(result.getId());
        }
        
        if(result.getErrors().size() > 0){
            System.debug(result.getErrors()[0].getMessage());
        }
    }

}