force-app/main/default/objects/Parts_Market_Factor__c/Parts_Market_Factor__c.object-meta.xml
<CustomObject>
    <label>Parts Market Factor</label>
    <nameField>
        <displayFormat>PMF-{00000}</displayFormat>
        <label>Parts Market Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Market_Factor__c/fields/Market_Factor__c.field-meta.xml
<CustomField>
    <fullName>Market_Factor__c</fullName>
    <label>Market Factor</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSSAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSSAC__c</fullName>
    <label>AMOSSAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NRRP__c.field-meta.xml
<CustomField>
    <fullName>NRRP__c</fullName>
    <label>NRRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAC__c.field-meta.xml
<CustomField>
    <fullName>SAC__c</fullName>
    <label>SAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <label>Parts</label>
</RecordType>

force-app/main/default/classes/ProductTriggerHelper.cls
public without sharing class ProductTriggerHelper {
    public static List<Product2> getPartItemsList(List<SObject> items) {
        Id partRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Parts').getRecordTypeId();

        List<Product2> partItems = new List<Product2>();
        for (Product2 item : (List<Product2>) items) {
            if (item.RecordTypeId == partRecordTypeId && String.isNotEmpty(item.AMOSSAC__c)) {
                partItems.add(item);
            }
        }
        return partItems;
    }

    public static Map<Id, SObject> getPartItemsMap(Map<Id, SObject> items) {
        Id partRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Parts').getRecordTypeId();

        Map<Id, SObject> partItems = new Map<Id, SObject>();
        for (Product2 item : (List<Product2>) items.values()) {
            if (item.RecordTypeId == partRecordTypeId && String.isNotEmpty(item.AMOSSAC__c)) {
                partItems.put(item.Id, item);
            }
        }
        return partItems;
    }

    public static void createPartsMarketFactors(List<Product2> partsList) {
        Set<String> newPartsSacSet = new Set<String>();
        Set<Id> nscDepartmentSet = new Set<Id>();
        for (Product2 prod : partsList) {
            newPartsSacSet.add(prod.AMOSSAC__c);
        }

        // Get Factors already exist
        Set<String> factorsNscSacSet = new Set<String>();
        for (Parts_Market_Factor__c factor : [
            SELECT SAC__c, 	Market_Factor__c
            FROM Parts_Market_Factor__c
            WHERE SAC__c IN :newPartsSacSet
        ]) {
            factorsNscSacSet.add(factor.SAC__c);
        }

        List<Parts_Market_Factor__c> insertList = new List<Parts_Market_Factor__c>();
        Set<String> insertSet = new Set<String>();
        for (Product2 part : partsList) {
            if (
                !factorsNscSacSet.contains(part.AMOSSAC__c) &&
                !insertSet.contains(part.AMOSSAC__c)
            ) {
                insertSet.add(part.AMOSSAC__c);
                insertList.add(
                    new Parts_Market_Factor__c(
                        SAC__c = part.AMOSSAC__c,
                        	Market_Factor__c = 1
                    )
                );
            }
        }
        if (!insertList.isEmpty()) {
            Database.insert(insertList);
        }
    }


    public static void updateNRRP(List<SObject> newItems, Map<Id, SObject> oldItems) {
        Set<String> partsSacSet = new Set<String>();
        for (Product2 prod : (List<Product2>) newItems) {
            partsSacSet.add(prod.AMOSSAC__c);
        }
        List<Parts_Market_Factor__c> partsMarketFactorList = [
            SELECT Id, SAC__c, Market_Factor__c
            FROM Parts_Market_Factor__c
            WHERE SAC__c IN :partsSacSet
        ];
        Map<String, Parts_Market_Factor__c> partsMarketFactorMap = new Map<String, Parts_Market_Factor__c>();
        for (Parts_Market_Factor__c factor : partsMarketFactorList) {
            partsMarketFactorMap.put(factor.SAC__c, factor);
        }

        if (Trigger.isUpdate) {
            for (Product2 prod : (List<Product2>) newItems) {
                if (prod.MSRP__c != ((Product2) oldItems.get(prod.Id)).MSRP__c) {
                    prod.NRRP__c =
                        prod.MSRP__c * partsMarketFactorMap.get(prod.AMOSSAC__c).Market_Factor__c;
                }
            }
        } else {
            for (Product2 prod : (List<Product2>) newItems) {
                if (partsMarketFactorMap.containsKey(prod.AMOSSAC__c)) {
                    prod.NRRP__c =
                        prod.MSRP__c * partsMarketFactorMap.get(prod.AMOSSAC__c).Market_Factor__c;
                }
            }
        }
    }

}