force-app/main/default/objects/Parts_Order__c/Parts_Order__c.object-meta.xml
<CustomObject>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order__c/fields/Parts_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order_Number__c</fullName>
    <displayFormat>PO-{00000}</displayFormat>
    <label>Parts Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/Parts_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Parts Order Line Item</label>
    <nameField>
        <label>Parts Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Ordered_Product__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/OrderedProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderedProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderedProduct</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Parts_Order__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order__c</fullName>
    <label>Parts Order</label>
    <referenceTo>Parts_Order__c</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <label>Quantity Requested</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PartsOrderController.cls
public with sharing class PartsOrderController {
    @AuraEnabled(Cacheable = true)
    public static Parts_Order__c serachPartsOrder(String searchKey) {
        String strKey = '%' + searchKey + '%';
        Parts_Order__c partsOrder = [ SELECT Id, Parts_Order_Number__c,  (SELECT Id, Name, 	Quantity_Requested__c, Ordered_Product__r.AMOSProductCode__c, Ordered_Product__r.AMOSSAC__c FROM Parts_Order_Line_Item__r)  FROM Parts_Order__c WHERE Parts_Order_Number__c LIKE: strKey LIMIT 1 ];
        if(partsOrder.Id == null) {
            throw new AuraHandledException('No Record Found');
        }
        return partsOrder; 
    }
}