force-app/main/default/objects/Parts_Order__c/Parts_Order__c.object-meta.xml
<CustomObject>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order__c/fields/Parts_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order_Number__c</fullName>
    <displayFormat>PO-{00000}</displayFormat>
    <label>Parts Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/Parts_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Parts Order Line Item</label>
    <nameField>
        <label>Parts Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Parts_Order__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order__c</fullName>
    <label>Parts Order</label>
    <referenceTo>Parts_Order__c</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/searchOrderedParts.cls
public with sharing class searchOrderedParts {
    @AuraEnabled(cacheable=true)
    public static list<Parts_Order__c> findParts(String searchKey) {
        string key = '%' + searchKey + '%';

        list<Parts_Order__c> partsList = [SELECT Id, Name, Parts_Order_Number__c FROM Parts_Order__c WHERE Name LIKE :key OR Parts_Order_Number__c LIKE :key];

        if (partsList.isEmpty()) {
            throw new AuraHandledException('No Records Found');
        }
        return partsList;
    } 

    @AuraEnabled
    public static List<Parts_Order_Line_Item__c> getPartsOrderLineItem(String partsOrderId) { 
        return [SELECT Id, Name FROM Parts_Order_Line_Item__c WHERE Parts_Order__c =: partsOrderId];
    }
}