force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Cost_Center_Code__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center_Code__c</fullName>
    <label>Cost Center Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/DealerCode__c.field-meta.xml
<CustomField>
    <fullName>DealerCode__c</fullName>
    <label>DealerCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/DistCode__c.field-meta.xml
<CustomField>
    <fullName>DistCode__c</fullName>
    <label>DistCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/MobisSuffix__c.field-meta.xml
<CustomField>
    <fullName>MobisSuffix__c</fullName>
    <label>MobisSuffix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/NSC_Department__c.field-meta.xml
<CustomField>
    <fullName>NSC_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSC Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Department</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIH__c/DIH__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DIH</label>
</CustomObject>

force-app/main/default/objects/Parts_Order__c/Parts_Order__c.object-meta.xml
<CustomObject>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order__c/fields/AMOS_Order_No__c.field-meta.xml
<CustomField>
    <fullName>AMOS_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>AMOS Order No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/AMOSDealerCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSDealerCode__c</fullName>
    <label>AMOSDealerCode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/AMOSMOBIS_Suffix__c.field-meta.xml
<CustomField>
    <fullName>AMOSMOBIS_Suffix__c</fullName>
    <label>AMOSMOBIS Suffix</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/AMOSOrderNo__c.field-meta.xml
<CustomField>
    <fullName>AMOSOrderNo__c</fullName>
    <externalId>true</externalId>
    <label>AMOSOrderNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/coDate__c.field-meta.xml
<CustomField>
    <fullName>coDate__c</fullName>
    <label>coDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Parts Order</relationshipLabel>
    <relationshipName>Parts_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/DepartmentCode__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCode__c</fullName>
    <label>DepartmentCode__c</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/IsOrderRequested__c.field-meta.xml
<CustomField>
    <fullName>IsOrderRequested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsOrderRequested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stock Order</fullName>
            </value>
            <value>
                <fullName>Emergency Order</fullName>
            </value>
            <value>
                <fullName>Accessory Order</fullName>
            </value>
            <value>
                <fullName>Campaign Order</fullName>
            </value>
            <value>
                <fullName>SST Order</fullName>
            </value>
            <value>
                <fullName>Market Support</fullName>
            </value>
            <value>
                <fullName>Claim Order</fullName>
            </value>
            <value>
                <fullName>Direct Takeout</fullName>
            </value>
            <value>
                <fullName>AM Order</fullName>
            </value>
            <value>
                <fullName>Wholesale Order</fullName>
            </value>
            <value>
                <fullName>Direct Purchasing Order</fullName>
            </value>
            <value>
                <fullName>Initial Order</fullName>
            </value>
            <value>
                <fullName>Book/EPC Order</fullName>
            </value>
            <value>
                <fullName>Accident Vehicle Support</fullName>
            </value>
            <value>
                <fullName>Oil Order</fullName>
            </value>
            <value>
                <fullName>Quotation Order</fullName>
            </value>
            <value>
                <fullName>Award Order</fullName>
            </value>
            <value>
                <fullName>Promotion Order</fullName>
            </value>
            <value>
                <fullName>VOR Order</fullName>
            </value>
            <value>
                <fullName>Warranty Order</fullName>
            </value>
            <value>
                <fullName>Taxi Order</fullName>
            </value>
            <value>
                <fullName>Vendor Direct Shipment Order</fullName>
            </value>
            <value>
                <fullName>D/C Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/OrderRecieveDate__c.field-meta.xml
<CustomField>
    <fullName>OrderRecieveDate__c</fullName>
    <label>OrderRecieveDate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order__c/fields/OrderRefNo__c.field-meta.xml
<CustomField>
    <fullName>OrderRefNo__c</fullName>
    <label>OrderRefNo</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/Parts_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Parts Order Line Item</label>
    <nameField>
        <label>Parts Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/AMOSDelAcceptYn__c.field-meta.xml
<CustomField>
    <fullName>AMOSDelAcceptYn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AMOSDelAcceptYn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/AMOSDiscountCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSDiscountCode__c</fullName>
    <label>AMOSDiscountCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/AMOSOrderNo__c.field-meta.xml
<CustomField>
    <fullName>AMOSOrderNo__c</fullName>
    <label>AMOSOrderNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/CancelCode__c.field-meta.xml
<CustomField>
    <fullName>CancelCode__c</fullName>
    <label>CancelCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/CancelDescription__c.field-meta.xml
<CustomField>
    <fullName>CancelDescription__c</fullName>
    <label>CancelDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Confirmed_Price__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Price__c</fullName>
    <label>Confirmed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Confirmed_Product__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Confirmed Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts Order Line Item (Confirmed Product)</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Confirmed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Free_Home_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Free_Home_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Free Home Delivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Order_Line_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_No__c</fullName>
    <label>Order Line No</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Ordered_Product__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/OrderedProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderedProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderedProduct</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Parts_Order__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order__c</fullName>
    <label>Parts Order</label>
    <referenceTo>Parts_Order__c</referenceTo>
    <relationshipLabel>Parts Order Line Item</relationshipLabel>
    <relationshipName>Parts_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parts_Order_Line_Item__c/fields/Quantity_Requested__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Requested__c</fullName>
    <label>Quantity Requested</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendPartOrderToAMOS.cls
public with sharing class SendPartOrderToAMOS {
    
    private static final String CONSTANT_AMOSENDPOINT = 'AMOS';
    private static final String CONSTANT_INTERFACENAME = 'IF_EU_CXP_AMOS_0001';
    private static String strTrackingId;
    private static Id partsOrderId;
    private static Map<String, String> partNoIdMap;   

    @AuraEnabled(cacheable=true)
    public static Parts_Order__c getProductRequestForAMOSCallout(Id productRequestId) { 
        Parts_Order__c prodRequest = [ 
            SELECT Id, CreatedDate, Department__r.Cost_Center_Code__c, Department__r.Department_Code__c, AMOSMOBIS_Suffix__c, Name, OrderRefNo__c, Order_Type__c, 
            Description__c, Flag__c, Department__r.DistCode__c, Department__r.DealerCode__c, Department__r.MobisSuffix__c, DepartmentCode__c, Dealer_Code__c, 
            (SELECT Id, Ordered_Product__r.ProductCode, Ordered_Product__r.Id, Order_Line_No__c, Quantity_Requested__c, Free_Home_Delivery__c, Description__c FROM Parts_Order_Line_Item__r)
            FROM Parts_Order__c
            WHERE Id =: productRequestId
        ];

        partNoIdMap = new Map<String, String>();
        for(Parts_Order_Line_Item__c po : prodRequest.Parts_Order_Line_Item__r) { 
            partNoIdMap.put(po.Ordered_Product__r.ProductCode, po.Ordered_Product__r.Id);
        }

        return prodRequest;
    }

    public static ResultWrapper sendProdReqToAMOS(List<Id> productRequestIdList) {
        ResultWrapper result = new ResultWrapper();
        Id productRequestId = productRequestIdList.get(0);
        partsOrderId = productRequestId;

        HttpRequest req = new HttpRequest();
        DIH__c obj = DIH__c.getInstance('Integration');
        String endpoint = obj.Endpoint__c;
        String username = obj.Username__c;
        String password = obj.Password__c;
//
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept', 'application/json');
        req.setEndpoint(endpoint);

        // Authentication needs to be done for the callout
        req.setMethod('POST');
        String body = generateBody(productRequestId);
        System.debug('req body : ' + body);
        req.setBody(body);
        req.setTimeout(120000);

        //System.enqueueJob(new SendPartOrderToAMOS_qu(req, partsOrderId, partNoIdMap));
        //result.resultStatus = true;
        //result.resultMessage = 'Request Complete';

        Http http = new Http();
        HttpResponse res = http.send(req);
        //Update based on response
        if (res.getBody() != null) {
            System.debug('res.getBody() : ' + res.getBody());
            result = updateProductRequest(res.getBody());
        } else {
            result.resultStatus = false;
            result.resultMessage = 'body => null';
        }

        System.debug('result : ' + JSON.serializePretty(result));
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static String generateBody(Id productRequestId) { 
        Parts_Order__c prodRequest = getProductRequestForAMOSCallout(productRequestId);

        CXP_AMOS_RestAPICalloutWrapper.T_DATA tData = new CXP_AMOS_RestAPICalloutWrapper.T_DATA();

        tData.DistributeCode = prodRequest.DepartmentCode__c;
        tData.DealerCode = prodRequest.Dealer_Code__c;
        tData.AMOSMOBISSuffix = prodRequest.Department__r.MobisSuffix__c;
        tData.ProductRequestNumber = prodRequest.Name;
        tData.OrderRefNo = prodRequest.OrderRefNo__c;
        tData.OrderType = prodRequest.Order_Type__c;
        tData.Description = prodRequest.Description__c;
        tData.Flag = 'Y';

        List<CXP_AMOS_RestAPICalloutWrapper.T_ITEM> tItemList = new List<CXP_AMOS_RestAPICalloutWrapper.T_ITEM>();
        for (Parts_Order_Line_Item__c prodReqLineItem : prodRequest.Parts_Order_Line_Item__r) { 
            CXP_AMOS_RestAPICalloutWrapper.T_ITEM tItem = new CXP_AMOS_RestAPICalloutWrapper.T_ITEM();
            tItem.DistributeCode = tData.DistributeCode;
            tItem.DealerCode = tData.DealerCode;
            tItem.AMOSMOBISSuffix = tData.AMOSMOBISSuffix;
            tItem.ProductRequestNumber = tData.ProductRequestNumber;
            tItem.OrderPartNo = prodReqLineItem.Ordered_Product__r.ProductCode;
            tItem.ProductRequestLineItemNumber = prodReqLineItem.Order_Line_No__c;
            tItem.QuantityRequested = string.valueOf(prodReqLineItem.Quantity_Requested__c);
            tItem.FreeHomeDelivery = '0';
            tItem.Description = prodReqLineItem.Description__c;
            tItemList.add(tItem);
        }

        CXP_AMOS_RestAPICalloutWrapper.Payload payload = new CXP_AMOS_RestAPICalloutWrapper.Payload();
        
        payload.T_DATA = tData;
        payload.T_ITEM = tItemList;

        CXP_AMOS_RestAPICalloutWrapper.Request request = new CXP_AMOS_RestAPICalloutWrapper.Request();
        request.payload = payload;

        CXP_AMOS_RestAPICalloutWrapper wrap = new CXP_AMOS_RestAPICalloutWrapper();
        wrap.request = request;

        strTrackingId = request.header.ifTrackingId;

        String json = JSON.serialize(wrap);
        return json;

    }

    public static ResultWrapper updateProductRequest(String jsonString) { 
        ResultWrapper result = new ResultWrapper();
        Schema.SObjectField externalIdProdReqLineItem = Parts_Order_Line_Item__c.fields.ExternalID__c;

        List<Parts_Order__c> productRequestListToUpdate = new List<Parts_Order__c>();
        List<Parts_Order_Line_Item__c> productRequestItemListToUpdate = new List<Parts_Order_Line_Item__c>();

        String trimStr = jsonString.replaceAll('\\\\', '');
        trimStr = trimStr.replaceAll('\n', '');
        trimStr = trimStr.replaceAll('\r', '');
        trimStr = trimStr.replaceAll('\t', '');

        CXP_AMOS_RestAPIWrapper wrapperList = (CXP_AMOS_RestAPIWrapper) System.JSON.deserialize(trimStr, CXP_AMOS_RestAPIWrapper.class);

        if (wrapperList.response.payload != null && wrapperList.response.payload.ES_DATA != null) { 
            CXP_AMOS_RestAPIWrapper.ES_DATA wrapper = wrapperList.response.payload.ES_DATA;

            Parts_Order__c pRequest = new Parts_Order__c();
            pRequest.Id = partsOrderId;

            pRequest.IsOrderRequested__c = wrapperList.response.header.ifResult == 'S' ? true : false;
            if(!pRequest.IsOrderRequested__c) { 
                update pRequest;
                result.resultStatus = false;
                result.resultMessage = wrapperList.response.header.ifFailMsg;
                return result;
            }
            result.orderNo = wrapperList.response.payload.ES_DATA.AMOSOrderNo;

            pRequest.AMOS_Order_No__c = wrapper.AMOSOrderNo;
            pRequest.AMOSDealerCode__c = wrapper.AMOSDealerCode;
            // if (String.isNotBlank(wrapper.OrderRecieveDate)) {
            //     Date jsonDateConverted = CXP_AMOS_PartsShipping.customDateConverter(wrapper.OrderRecieveDate);
            //     if (jsonDateConverted != null) {
            //         pRequest.OrderRecieveDate__c = jsonDateConverted;
            //     }
            // }
            pRequest.Order_Type__c = wrapper.OrderType;
            pRequest.OrderRefNo__c = wrapper.OrderRefNo;
            pRequest.Description__c = wrapper.Description;
            pRequest.Flag__c = wrapper.Flag == 'Y' ? true : false;
            // if (String.isNotBlank(wrapper.CoDate)) {
            //     Date jsonDateConverted = CXP_AMOS_PartsShipping.customDateConverter(wrapper.CoDate);
            //     if (jsonDateConverted != null) {
            //         pRequest.CoDate__c = jsonDateConverted;
            //     }
            // }
            // pRequest.ConfirmedDate__c = CXP_AMOS_PartsShipping.customDateConverter(wrapper.OrderRecieveDate);
            productRequestListToUpdate.add(pRequest);

            if (wrapperList.response.payload.ES_ITEM != null) { 
                for (CXP_AMOS_RestAPIWrapper.ES_ITEM pReqLineItemWrapper : wrapperList.response.payload.ES_ITEM) { 

                    String ExteranlKeypRequestLineItemLineItem;
                    ExteranlKeypRequestLineItemLineItem = partsOrderId + '_' + partNoIdMap.get(pReqLineItemWrapper.OrderedPartNo);

                    Parts_Order_Line_Item__c pRequestLineItem = new Parts_Order_Line_Item__c();
                    pRequestLineItem.ExternalID__c = ExteranlKeypRequestLineItemLineItem;

                    pRequestLineItem.Confirmed_Product__c = partNoIdMap.get(pReqLineItemWrapper.AMOSConfirmPartNo);
                    pRequestLineItem.Confirmed_Quantity__c = Integer.valueOf(pReqLineItemWrapper.AMOSConfirmQty);
                    if(pReqLineItemWrapper.AMOSDelAcceptYn == '1') pRequestLineItem.AMOSDelAcceptYn__c = true; else pRequestLineItem.AMOSDelAcceptYn__c = false;
                    pRequestLineItem.AMOSDiscountCode__c = pReqLineItemWrapper.AMOSDiscountCode;
                    pRequestLineItem.Confirmed_Price__c = Decimal.valueOf(pReqLineItemWrapper.UnitPrice);
                    pRequestLineItem.Description__c = pReqLineItemWrapper.Description;
                    pRequestLineItem.AMOSOrderNo__c = pReqLineItemWrapper.AMOSOrderNo;
                    pRequestLineItem.CancelCode__c = pReqLineItemWrapper.CancelCode;
                    pRequestLineItem.CancelDescription__c = pReqLineItemWrapper.CancelDescription;

                    productRequestItemListToUpdate.add(pRequestLineItem);


                }
            }
        } else {
            result.resultStatus = false;
            result.resultMessage = wrapperList.response.header.ifFailMsg;
            return result;
        }

        //DML Update
        try {
            if (!productRequestListToUpdate.isEmpty()) {
                update productRequestListToUpdate;
            }
            if (!productRequestItemListToUpdate.isEmpty()) {
                Database.upsert(productRequestItemListToUpdate, externalIdProdReqLineItem, true);
            }

            result.resultStatus = true;
            return result;

        } catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage() + ', ' + e.getStackTraceString());

            result.resultStatus = false;
            result.resultMessage = e.getMessage() + ', ' + e.getStackTraceString();
            return result;
        }
    }
    
    public class ResultWrapper {
        @AuraEnabled
        public String orderNo;
        @AuraEnabled
        public String gmeOrderNo;
        @AuraEnabled
        public Boolean resultStatus;
        @AuraEnabled
        public String resultMessage;

    }
    
}