force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/NSC_Department__c.field-meta.xml
<CustomField>
    <fullName>NSC_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSC Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Department</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSCertificateOfOrigin__c.field-meta.xml
<CustomField>
    <fullName>AMOSCertificateOfOrigin__c</fullName>
    <label>AMOSCertificateOfOrigin</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSCharAnalysisCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSCharAnalysisCode__c</fullName>
    <label>AMOSCharAnalysisCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSCompanyCode__c</fullName>
    <label>AMOSCompanyCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSCompanyKindCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSCompanyKindCode__c</fullName>
    <label>AMOSCompanyKindCode</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSDimensionalMeasurement__c.field-meta.xml
<CustomField>
    <fullName>AMOSDimensionalMeasurement__c</fullName>
    <label>AMOSDimensionalMeasurement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSDiscountGroup__c.field-meta.xml
<CustomField>
    <fullName>AMOSDiscountGroup__c</fullName>
    <label>AMOSDiscountGroup</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSDisposableClass__c.field-meta.xml
<CustomField>
    <fullName>AMOSDisposableClass__c</fullName>
    <label>AMOSDisposableClass</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSDistributorSegment__c.field-meta.xml
<CustomField>
    <fullName>AMOSDistributorSegment__c</fullName>
    <label>AMOSDistributorSegment</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSHSCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSHSCode__c</fullName>
    <label>AMOSHSCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSLAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSLAC__c</fullName>
    <label>AMOSLAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSLargeGroup__c.field-meta.xml
<CustomField>
    <fullName>AMOSLargeGroup__c</fullName>
    <label>AMOSLargeGroup</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSLegalCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSLegalCode__c</fullName>
    <label>AMOSLegalCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSMAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSMAC__c</fullName>
    <label>AMOSMAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSPackagingunit__c.field-meta.xml
<CustomField>
    <fullName>AMOSPackagingunit__c</fullName>
    <label>AMOSPackagingunit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSPartName__c.field-meta.xml
<CustomField>
    <fullName>AMOSPartName__c</fullName>
    <label>AMOSPartName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSPartNameNative__c.field-meta.xml
<CustomField>
    <fullName>AMOSPartNameNative__c</fullName>
    <label>AMOSPartNameNative</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCategoryCode__c</fullName>
    <label>AMOSProductCategoryCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCode__c</fullName>
    <label>AMOSProductCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCodeNEW__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCodeNEW__c</fullName>
    <label>AMOSProductCodeNEW</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductCodeOLD__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductCodeOLD__c</fullName>
    <label>AMOSProductCodeOLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSProductTypeCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSProductTypeCode__c</fullName>
    <label>AMOSProductTypeCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSRemanufacturePartCode__c.field-meta.xml
<CustomField>
    <fullName>AMOSRemanufacturePartCode__c</fullName>
    <label>AMOSRemanufacturePartCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSSAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSSAC__c</fullName>
    <label>AMOSSAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSWeightMeasurement__c.field-meta.xml
<CustomField>
    <fullName>AMOSWeightMeasurement__c</fullName>
    <label>AMOSWeightMeasurement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CurrencyIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyIsoCode__c</fullName>
    <label>CurrencyIsoCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DAOSMinimumOrderQuantity__c.field-meta.xml
<CustomField>
    <fullName>DAOSMinimumOrderQuantity__c</fullName>
    <label>DAOSMinimumOrderQuantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NSC_Department__c.field-meta.xml
<CustomField>
    <fullName>NSC_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSC Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDealerPriceDLY__c.field-meta.xml
<CustomField>
    <fullName>ProductDealerPriceDLY__c</fullName>
    <label>ProductDealerPriceDLY</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDealerPriceSTK__c.field-meta.xml
<CustomField>
    <fullName>ProductDealerPriceSTK__c</fullName>
    <label>ProductDealerPriceSTK</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDealerPriceVOR__c.field-meta.xml
<CustomField>
    <fullName>ProductDealerPriceVOR__c</fullName>
    <label>ProductDealerPriceVOR</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDiscountRateDLY__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscountRateDLY__c</fullName>
    <label>ProductDiscountRateDLY</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDiscountRateSTK__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscountRateSTK__c</fullName>
    <label>ProductDiscountRateSTK</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDiscountRateVOR__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscountRateVOR__c</fullName>
    <label>ProductDiscountRateVOR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductPriceBasic__c.field-meta.xml
<CustomField>
    <fullName>ProductPriceBasic__c</fullName>
    <label>ProductPriceBasic</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductPriceRetail__c.field-meta.xml
<CustomField>
    <fullName>ProductPriceRetail__c</fullName>
    <label>ProductPriceRetail</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>ProductType</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CXP_AMOS_PartsMaster_API.cls
@RestResource(urlMapping='/CXP_AMOS_PartsMaster/*')
global with sharing class CXP_AMOS_PartsMaster_API {
    @HttpPost
    global static void partsInsert() {
        RestRequest  request = RestContext.request;
        RestResponse response = RestContext.response;

        CXP_AMOS_PartsMaster_APIWrapper bodyWrapper = CXP_AMOS_PartsMaster_APIWrapper.parse(request.requestBody.toString());
        CXP_AMOS_PartsMaster_APIWrapper.Response responseInstance = new CXP_AMOS_PartsMaster_APIWrapper.Response(
            bodyWrapper.request.header.ifTrackingId
        );

        Schema.SObjectField externalId = Product2.Fields.External_Key__c;
        Map<String, Id> departmentCodeMap = new Map<String, Id>();
        List<Department__c> departmentList = [
            SELECT Id, Department_Code__c
            FROM Department__c
            WHERE RecordType.Name = 'NSC Department'
        ];
        for (Department__c department : departmentList) {
            departmentCodeMap.put(department.Department_Code__c, department.Id);
        }

        Map<String, Product2> productMap = new Map<String, Product2>();
        for (CXP_AMOS_PartsMaster_APIWrapper.T_DATA bodyItem : bodyWrapper.request.payload.T_DATA) {
            Product2 product = new Product2();
            if (String.isBlank(bodyItem.AMOSProductCode)) {
                populateResponseErrorMessage(responseInstance, 'E', ' ', 'VIN value is empty');
                break;
            }
            product.Name = bodyItem.AMOSPartName;
            product.AMOSCompanyKindCode__c	= bodyItem.AMOSCompanyKindCode;
            product.AMOSProductCode__c = bodyItem.AMOSProductCode;
            product.AMOSPartNameNative__c = bodyItem.AMOSPartNameNative;
            product.AMOSPartName__c = bodyItem.AMOSPartName;
            product.AMOSProductCodeNEW__c = bodyItem.AMOSProductCodeNEW;
            product.AMOSProductCodeOLD__c = bodyItem.AMOSProductCodeOLD;
            product.ProductType__c = bodyItem.ProductType;
            product.AMOSDisposableClass__c = bodyItem.AMOSDisposableClass;
            product.AMOSPackagingunit__c = bodyItem.AMOSPackagingunit;
            product.AMOSDimensionalMeasurement__c = bodyItem.AMOSDimensionalMeasurement;
            product.AMOSWeightMeasurement__c = bodyItem.AMOSWeightMeasurement;
            product.Width__c = bodyItem.Width;
            product.Length__c = bodyItem.Length;
            product.Height__c = bodyItem.Height;
            product.Weight__c = bodyItem.Weight;
            product.CurrencyIsoCode__c = bodyItem.CurrencyIsoCode;
            product.ProductPriceRetail__c = bodyItem.ProductPriceRetail;
            product.ProductPriceBasic__c = bodyItem.ProductPriceBasic;
            product.MSRP__c = bodyItem.ProductPriceMSRP;
            product.ProductDealerPriceVOR__c = bodyItem.ProductDealerPriceVOR;
            product.ProductDealerPriceDLY__c = bodyItem.ProductDealerPriceDLY;
            product.ProductDealerPriceStk__c = bodyItem.ProductDealerPriceStk;
            product.AMOSDiscountGroup__c = bodyItem.AMOSDiscountGroup;
            product.ProductDiscountRateVOR__c = bodyItem.ProductDiscountRateVOR;
            product.ProductDiscountRateDLY__c = bodyItem.ProductDiscountRateDLY;
            product.ProductDiscountRateSTK__c = bodyItem.ProductDiscountRateSTK;
            product.AMOSLargeGroup__c = bodyItem.AMOSLargeGroup;
            product.AMOSDistributorSegment__c = bodyItem.AMOSDistributorSegment;
            product.DAOSMinimumOrderQuantity__c = bodyItem.DAOSMinimumOrderQuantity;
            product.AMOSCertificateOfOrigin__c = bodyItem.AMOSCertificateOfOrigin;
            product.AMOSRemanufacturePartCode__c = bodyItem.AMOSRemanufacturePartCode;
            product.AMOSCompanyCode__c = bodyItem.AMOSCompanyCode;
            product.AMOSLegalCode__c = bodyItem.AMOSLegalCode;
            product.AMOSHSCode__c = bodyItem.AMOSHSCode;
            product.AMOSLAC__c = bodyItem.AMOSLAC;
            product.AMOSMAC__c = bodyItem.AMOSMAC;
            product.AMOSSAC__c = bodyItem.AMOSSAC;
            product.AMOSProductTypeCode__c = bodyItem.AMOSProductTypeCode;
            product.AMOSProductCategoryCode__c = bodyItem.AMOSProductCategoryCode;
            product.AMOSCharAnalysisCode__c = bodyItem.AMOSCharAnalysisCode;
            product.StartDate__c = bodyItem.StartDate;
            product.EndDate__c = bodyItem.EndDate;
            product.External_Key__c = bodyItem.AMOSCompanyKindCode + bodyItem.AMOSProductCode;
            product.NSC_Department__c = departmentCodeMap.get(product.AMOSCompanyKindCode__c);
            productMap.put(product.External_Key__c, product);
        }

        if (String.isBlank(responseInstance.response.payload.ErrorMsg)) {
            Database.upsert(productMap.values(), externalId, true);
            responseInstance.response.payload.ResultCode = 'Z';
            responseInstance.response.payload.ErrorCode = ' ';
            responseInstance.response.payload.ErrorMsg = ' ';
        }

        String responseJson = System.JSON.serialize(responseInstance, false);
        response.responseBody = Blob.valueOf(responseJson);
    }

    private static void populateResponseErrorMessage(
        CXP_AMOS_PartsMaster_APIWrapper.Response response,
        String resultCode,
        String errorCode,
        String errorMsg
    ) {
        response.response.payload.ResultCode = resultCode;
        response.response.payload.ErrorCode = errorCode;
        response.response.payload.ErrorMsg = errorMsg;
    }
}
//