force-app/main/default/objects/GME_TriggerSettings__c/GME_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is for deactivating triggers</description>
    <label>GME_TriggerSettings</label>
</CustomObject>

force-app/main/default/objects/GME_TriggerSettings__c/fields/PartsMarketFactorTriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>PartsMarketFactorTriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PartsMarketFactorTriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parts_Market_Factor__c/Parts_Market_Factor__c.object-meta.xml
<CustomObject>
    <label>Parts Market Factor</label>
    <nameField>
        <displayFormat>PMF-{00000}</displayFormat>
        <label>Parts Market Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Market_Factor__c/fields/Market_Factor__c.field-meta.xml
<CustomField>
    <fullName>Market_Factor__c</fullName>
    <label>Market Factor</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AMOSSAC__c.field-meta.xml
<CustomField>
    <fullName>AMOSSAC__c</fullName>
    <label>AMOSSAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NRRP__c.field-meta.xml
<CustomField>
    <fullName>NRRP__c</fullName>
    <label>NRRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NSC_Department__c.field-meta.xml
<CustomField>
    <fullName>NSC_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSC Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAC__c.field-meta.xml
<CustomField>
    <fullName>SAC__c</fullName>
    <label>SAC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PartsMarketFactorTriggerHandler.cls
public with sharing class PartsMarketFactorTriggerHandler implements GME_ITriggerHandler{
    public static Boolean TriggerDisabled = false;

    public Boolean IsDisabled() { 
        if (GME_TriggerSettings__c.getOrgDefaults().PartsMarketFactorTriggerDisabled__c == true) { 
            return true;
        } else { 
            return TriggerDisabled;
        }
    }
    public void BeforeInsert(List<SObject> newItems) {
    }

    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
    }

    public void BeforeDelete(Map<Id, SObject> oldItems) {
    }

    public void AfterInsert(Map<Id, SObject> newItems) { 
        if (IsDisabled()) return;
        updatePartsNRRP(newItems);
    }

    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) { 
        updatePartsNRRP(newItems);
    }
    public void AfterDelete(Map<Id, SObject> oldItems) {
    }

    public void AfterUndelete(Map<Id, SObject> oldItems) {
    }
    public static void updatePartsNRRP(Map<Id, SObject> newItems) { 
        Set<String> marketFactorSacSet = new Set<String>();
        for (Parts_Market_Factor__c factor : (List<Parts_Market_Factor__c>) newItems.values()) { 
            marketFactorSacSet.add(factor.SAC__c);
        }

        List<Product2> updateParts = new List<Product2>();
        Map<Id, Product2> targetParts = new Map<Id, Product2>(
            [
                SELECT Id, NSC_Department__c, AMOSSAC__c, MSRP__c, NRRP__c
                FROM Product2
                WHERE AMOSSAC__c IN :marketFactorSacSet AND RecordType.Name = 'Part'
            ]
        );

        for (Product2 part : targetParts.values()) { 
            for (Parts_Market_Factor__c factor : (List<Parts_Market_Factor__c>) newItems.values()) { 
                if (factor.SAC__c == part.AMOSSAC__c) { 
                    if (part.MSRP__c != null) { 
                        part.NRRP__c = factor.Market_Factor__c = part.MSRP__c;                    
                        break;
                    }
                }
            }
        }
        if (updateParts.size() > 0) { 
            Database.update(updateParts);
        }
    }
}